import { db } from './lib/db.js';
import {
  schoolsTable, coursesTable, blogPostsTable, faqsTable,
  testimonialsTable, siteSettingsTable,
} from '@workspace/db';

async function seedContent() {
  console.log('🌱 Seeding content...');

  // ─── Schools ────────────────────────────────────────────────────────────────
  console.log('📚 Seeding schools...');
  await db.insert(schoolsTable).values([
    {
      slug: 'cia',
      name: 'CIA - Center for Intensive American English',
      nameTh: 'เซนเตอร์ ฟอร์ อินเทนซิฟ อเมริกัน อิงลิช',
      tagline: 'Premier English school in Cebu with American curriculum',
      taglineTh: 'โรงเรียนภาษาอังกฤษชั้นนำในเซบูที่ใช้หลักสูตรอเมริกัน',
      city: 'Cebu',
      country: 'Philippines',
      rating: 4.8,
      studentsCount: '500+',
      nationalityCount: '30+',
      foundedYear: 1983,
      description: 'CIA is one of the most prestigious English language schools in the Philippines, offering intensive American English programs.',
      descriptionTh: 'CIA เป็นหนึ่งในโรงเรียนภาษาอังกฤษที่มีชื่อเสียงที่สุดในฟิลิปปินส์ โดยเปิดสอนหลักสูตรภาษาอังกฤษแบบอเมริกันอย่างเข้มข้น',
      highlights: ['American ESL Curriculum', 'Small Class Sizes', 'Certified Teachers', 'Modern Facilities'],
      facilities: ['Swimming Pool', 'Gym', 'Library', 'Cafeteria', 'Wi-Fi'],
      programs: [
        { name: 'General English', nameTh: 'ภาษาอังกฤษทั่วไป', duration: '4-52 weeks', w4: 800, w8: 1500, w12: 2100 },
        { name: 'IELTS Preparation', nameTh: 'เตรียมสอบ IELTS', duration: '4-24 weeks', w4: 900, w8: 1700, w12: 2400 },
      ],
      accentClass: 'from-blue-500 to-blue-700',
      tags: ['IELTS', 'General English', 'Business English'],
      isFeatured: true,
      isActive: true,
      sortOrder: 1,
    },
    {
      slug: 'qq-english',
      name: 'QQ English',
      nameTh: 'คิวคิว อิงลิช',
      tagline: 'Dynamic English school with innovative teaching methods',
      taglineTh: 'โรงเรียนภาษาอังกฤษที่มีวิธีการสอนที่สร้างสรรค์',
      city: 'Cebu',
      country: 'Philippines',
      rating: 4.7,
      studentsCount: '400+',
      nationalityCount: '25+',
      foundedYear: 2000,
      description: 'QQ English is known for its innovative Circle Method teaching approach and diverse student community.',
      descriptionTh: 'QQ English ขึ้นชื่อเรื่องวิธีการสอนแบบ Circle Method ที่สร้างสรรค์และชุมชนนักเรียนที่หลากหลาย',
      highlights: ['Circle Method Teaching', 'Filipino & Foreign Teachers', 'Social Activities', 'Beach Location'],
      facilities: ['Pool', 'Study Rooms', 'Cafeteria', 'Sports Area', 'Wi-Fi'],
      programs: [
        { name: 'Power English', nameTh: 'พาวเวอร์ อิงลิช', duration: '4-24 weeks', w4: 750, w8: 1400, w12: 2000 },
        { name: 'TOEIC Program', nameTh: 'โปรแกรม TOEIC', duration: '4-16 weeks', w4: 800, w8: 1500, w12: 2100 },
      ],
      accentClass: 'from-green-500 to-green-700',
      tags: ['TOEIC', 'General English', 'Circle Method'],
      isFeatured: true,
      isActive: true,
      sortOrder: 2,
    },
    {
      slug: 'philinter',
      name: 'Philinter Language Center',
      nameTh: 'ฟิลอินเตอร์ แลงกวิจ เซ็นเตอร์',
      tagline: 'Comprehensive English programs for all levels',
      taglineTh: 'โปรแกรมภาษาอังกฤษครบวงจรสำหรับทุกระดับ',
      city: 'Cebu',
      country: 'Philippines',
      rating: 4.6,
      studentsCount: '350+',
      nationalityCount: '20+',
      foundedYear: 2001,
      description: 'Philinter Language Center offers comprehensive English programs with a focus on practical communication skills.',
      descriptionTh: 'Philinter Language Center เปิดสอนโปรแกรมภาษาอังกฤษครบวงจรโดยเน้นทักษะการสื่อสารในทางปฏิบัติ',
      highlights: ['One-on-One Classes', 'IELTS & TOEIC', 'Cultural Activities', 'Affordable Rates'],
      facilities: ['Library', 'Computer Lab', 'Cafeteria', 'Wi-Fi', 'Dormitory'],
      programs: [
        { name: 'ESL General', nameTh: 'ESL ทั่วไป', duration: '4-24 weeks', w4: 700, w8: 1300, w12: 1900 },
      ],
      accentClass: 'from-purple-500 to-purple-700',
      tags: ['ESL', 'IELTS', 'TOEIC'],
      isFeatured: false,
      isActive: true,
      sortOrder: 3,
    },
    {
      slug: 'bcebu',
      name: "B'Cebu Language School",
      nameTh: 'บีเซบู แลงกวิจ สคูล',
      tagline: 'Top-rated school with premium facilities',
      taglineTh: 'โรงเรียนระดับสูงพร้อมสิ่งอำนวยความสะดวกระดับพรีเมียม',
      city: 'Cebu',
      country: 'Philippines',
      rating: 4.7,
      studentsCount: '300+',
      nationalityCount: '22+',
      foundedYear: 2008,
      description: "B'Cebu Language School is a premium English school known for its excellent facilities and high-quality teaching.",
      descriptionTh: "B'Cebu Language School เป็นโรงเรียนภาษาอังกฤษระดับพรีเมียมที่ขึ้นชื่อเรื่องสิ่งอำนวยความสะดวกและการสอนคุณภาพสูง",
      highlights: ['Premium Facilities', 'Certified Filipino Teachers', 'Modern Classrooms', 'Visa Support'],
      facilities: ['Olympic Pool', 'Gym', 'Study Hall', 'Cafeteria', 'Wi-Fi'],
      programs: [
        { name: 'Intensive English', nameTh: 'อิงลิชอินเทนซิฟ', duration: '4-24 weeks', w4: 850, w8: 1600, w12: 2300 },
      ],
      accentClass: 'from-orange-500 to-orange-700',
      tags: ['Intensive', 'Premium', 'IELTS'],
      isFeatured: true,
      isActive: true,
      sortOrder: 4,
    },
    {
      slug: 'cpils',
      name: 'CPILS - Cebu Premier International Language School',
      nameTh: 'ซีพีไอแอลเอส เซบู พรีเมียร์ อินเตอร์เนชั่นแนล แลงกวิจ สคูล',
      tagline: 'Quality English education in the heart of Cebu',
      taglineTh: 'การศึกษาภาษาอังกฤษคุณภาพในใจกลางเซบู',
      city: 'Cebu',
      country: 'Philippines',
      rating: 4.5,
      studentsCount: '250+',
      nationalityCount: '18+',
      foundedYear: 2005,
      description: 'CPILS offers premium English language programs with certified teachers and modern facilities.',
      descriptionTh: 'CPILS เปิดสอนโปรแกรมภาษาอังกฤษระดับพรีเมียมพร้อมครูที่ได้รับการรับรองและสิ่งอำนวยความสะดวกทันสมัย',
      highlights: ['Certified Teachers', 'Small Classes', 'IELTS Prep', 'City Location'],
      facilities: ['Study Rooms', 'Library', 'Cafeteria', 'Wi-Fi'],
      programs: [
        { name: 'General English', nameTh: 'ภาษาอังกฤษทั่วไป', duration: '4-24 weeks', w4: 720, w8: 1350, w12: 1950 },
      ],
      accentClass: 'from-teal-500 to-teal-700',
      tags: ['General English', 'IELTS'],
      isFeatured: false,
      isActive: true,
      sortOrder: 5,
    },
    {
      slug: 'ev-academy',
      name: 'EV Academy',
      nameTh: 'อีวี อคาเดมี',
      tagline: 'Excellence in English language education',
      taglineTh: 'ความเป็นเลิศในการศึกษาภาษาอังกฤษ',
      city: 'Cebu',
      country: 'Philippines',
      rating: 4.6,
      studentsCount: '280+',
      nationalityCount: '20+',
      foundedYear: 2003,
      description: 'EV Academy provides excellent English language programs with a focus on speaking and listening skills.',
      descriptionTh: 'EV Academy มีโปรแกรมภาษาอังกฤษที่ยอดเยี่ยมโดยเน้นทักษะการพูดและการฟัง',
      highlights: ['Speaking Focus', 'One-on-One Sessions', 'Modern Campus', 'Visa Support'],
      facilities: ['Sports Facilities', 'Library', 'Cafeteria', 'Wi-Fi'],
      programs: [
        { name: 'Speaking & Listening', nameTh: 'การพูดและการฟัง', duration: '4-24 weeks', w4: 730, w8: 1380, w12: 1980 },
      ],
      accentClass: 'from-red-500 to-red-700',
      tags: ['Speaking', 'TOEIC', 'General English'],
      isFeatured: false,
      isActive: true,
      sortOrder: 6,
    },
    {
      slug: 'smeag',
      name: 'SMEAG Capital',
      nameTh: 'เอสเอ็มอีเอจี แคปิตอล',
      tagline: 'World-class English school with campus life',
      taglineTh: 'โรงเรียนภาษาอังกฤษระดับโลกพร้อมชีวิตในแคมปัส',
      city: 'Cebu',
      country: 'Philippines',
      rating: 4.9,
      studentsCount: '600+',
      nationalityCount: '35+',
      foundedYear: 1993,
      description: 'SMEAG Capital is one of the largest and most prestigious English schools in the Philippines with world-class facilities.',
      descriptionTh: 'SMEAG Capital เป็นหนึ่งในโรงเรียนภาษาอังกฤษที่ใหญ่และมีชื่อเสียงที่สุดในฟิลิปปินส์พร้อมสิ่งอำนวยความสะดวกระดับโลก',
      highlights: ['World-Class Facilities', 'IELTS Platinum Center', 'Large Campus', 'Strict Study System'],
      facilities: ['Olympic Pool', 'Gym', 'Sports Courts', 'Library', 'Cafeteria', 'Convenience Store'],
      programs: [
        { name: 'ESL Standard', nameTh: 'ESL สแตนดาร์ด', duration: '4-52 weeks', w4: 950, w8: 1800, w12: 2600, w24: 4800 },
        { name: 'IELTS Preparation', nameTh: 'เตรียมสอบ IELTS', duration: '4-24 weeks', w4: 1000, w8: 1900, w12: 2700 },
      ],
      accentClass: 'from-indigo-500 to-indigo-700',
      tags: ['IELTS', 'Intensive', 'Premium', 'Campus Life'],
      isFeatured: true,
      isActive: true,
      sortOrder: 7,
    },
    {
      slug: 'pines',
      name: 'PINES International Academy',
      nameTh: 'ไพนส์ อินเตอร์เนชั่นแนล อคาเดมี',
      tagline: 'English excellence in the cool highlands of Baguio',
      taglineTh: 'ความเป็นเลิศด้านภาษาอังกฤษในที่ราบสูงอันเย็นสบายของบาเกียว',
      city: 'Baguio',
      country: 'Philippines',
      rating: 4.7,
      studentsCount: '450+',
      nationalityCount: '28+',
      foundedYear: 1998,
      description: 'PINES International Academy is located in the cool highlands of Baguio, offering excellent English programs in a refreshing environment.',
      descriptionTh: 'PINES International Academy ตั้งอยู่ในที่ราบสูงอันเย็นสบายของบาเกียว เปิดสอนโปรแกรมภาษาอังกฤษที่ยอดเยี่ยมในสภาพแวดล้อมที่สดชื่น',
      highlights: ['Cool Weather', 'City Center Location', 'High Quality Teachers', 'Strict No-Korean Policy'],
      facilities: ['Library', 'Study Rooms', 'Cafeteria', 'Wi-Fi', 'Gym'],
      programs: [
        { name: 'General English', nameTh: 'ภาษาอังกฤษทั่วไป', duration: '4-24 weeks', w4: 780, w8: 1480, w12: 2150 },
        { name: 'TOEFL/IELTS', nameTh: 'TOEFL/IELTS', duration: '4-16 weeks', w4: 850, w8: 1600, w12: 2300 },
      ],
      accentClass: 'from-emerald-500 to-emerald-700',
      tags: ['Baguio', 'IELTS', 'TOEFL', 'Cool Weather'],
      isFeatured: true,
      isActive: true,
      sortOrder: 8,
    },
  ]).onConflictDoNothing();

  // ─── Courses ────────────────────────────────────────────────────────────────
  console.log('📖 Seeding courses...');
  await db.insert(coursesTable).values([
    {
      slug: 'general-english',
      title: 'General English',
      titleTh: 'ภาษาอังกฤษทั่วไป',
      subtitle: 'Build a strong foundation in English',
      subtitleTh: 'สร้างรากฐานภาษาอังกฤษที่แข็งแกร่ง',
      iconName: 'BookOpen',
      description: 'Our General English program covers all four skills: reading, writing, listening, and speaking. Suitable for all levels.',
      descriptionTh: 'โปรแกรมภาษาอังกฤษทั่วไปของเราครอบคลุมทักษะทั้งสี่: การอ่าน การเขียน การฟัง และการพูด เหมาะสำหรับทุกระดับ',
      duration: '4-52 weeks',
      durationTh: '4-52 สัปดาห์',
      suitableFor: 'Beginners to Advanced learners',
      suitableForTh: 'ผู้เรียนตั้งแต่ระดับเริ่มต้นจนถึงขั้นสูง',
      priceDisplay: 'from $700/4 weeks',
      priceDisplayTh: 'เริ่มต้น ฿25,000/4 สัปดาห์',
      colorClass: 'bg-blue-500',
      badge: 'Most Popular',
      badgeTh: 'ยอดนิยม',
      features: ['Speaking & Listening', 'Grammar & Vocabulary', 'Reading & Writing', 'Cultural Immersion'],
      isFeatured: true,
      isActive: true,
      sortOrder: 1,
    },
    {
      slug: 'ielts-preparation',
      title: 'IELTS Preparation',
      titleTh: 'เตรียมสอบ IELTS',
      subtitle: 'Achieve your target IELTS band score',
      subtitleTh: 'บรรลุคะแนน IELTS ตามเป้าหมายของคุณ',
      iconName: 'Target',
      description: 'Intensive IELTS preparation program designed to help you achieve your target band score efficiently.',
      descriptionTh: 'โปรแกรมเตรียมสอบ IELTS แบบเข้มข้นที่ออกแบบมาเพื่อช่วยให้คุณได้คะแนน band ตามเป้าหมายอย่างมีประสิทธิภาพ',
      duration: '4-24 weeks',
      durationTh: '4-24 สัปดาห์',
      suitableFor: 'Students planning to study abroad or immigrate',
      suitableForTh: 'นักเรียนที่วางแผนศึกษาต่อต่างประเทศหรืออพยพ',
      priceDisplay: 'from $900/4 weeks',
      priceDisplayTh: 'เริ่มต้น ฿32,000/4 สัปดาห์',
      colorClass: 'bg-indigo-500',
      badge: 'Exam Focused',
      badgeTh: 'เน้นการสอบ',
      features: ['IELTS Mock Tests', 'Writing Task 1 & 2', 'Speaking Practice', 'Reading Strategies'],
      isFeatured: true,
      isActive: true,
      sortOrder: 2,
    },
    {
      slug: 'toeic-preparation',
      title: 'TOEIC Preparation',
      titleTh: 'เตรียมสอบ TOEIC',
      subtitle: 'Boost your TOEIC score for career advancement',
      subtitleTh: 'เพิ่มคะแนน TOEIC เพื่อความก้าวหน้าในอาชีพ',
      iconName: 'Briefcase',
      description: 'TOEIC preparation program focused on listening and reading skills for professional certification.',
      descriptionTh: 'โปรแกรมเตรียมสอบ TOEIC ที่มุ่งเน้นทักษะการฟังและการอ่านสำหรับการรับรองระดับมืออาชีพ',
      duration: '4-16 weeks',
      durationTh: '4-16 สัปดาห์',
      suitableFor: 'Working professionals and job seekers',
      suitableForTh: 'มืออาชีพที่ทำงานและผู้หางาน',
      priceDisplay: 'from $750/4 weeks',
      priceDisplayTh: 'เริ่มต้น ฿26,500/4 สัปดาห์',
      colorClass: 'bg-green-500',
      badge: 'Career Boost',
      badgeTh: 'เพิ่มพูนอาชีพ',
      features: ['Listening Test Practice', 'Reading Comprehension', 'Vocabulary Building', 'Mock TOEIC Tests'],
      isFeatured: true,
      isActive: true,
      sortOrder: 3,
    },
    {
      slug: 'business-english',
      title: 'Business English',
      titleTh: 'ภาษาอังกฤษธุรกิจ',
      subtitle: 'Professional English for the workplace',
      subtitleTh: 'ภาษาอังกฤษระดับมืออาชีพสำหรับที่ทำงาน',
      iconName: 'TrendingUp',
      description: 'Business English program covering professional communication, presentations, negotiations, and email writing.',
      descriptionTh: 'โปรแกรมภาษาอังกฤษธุรกิจที่ครอบคลุมการสื่อสารระดับมืออาชีพ การนำเสนอ การเจรจา และการเขียนอีเมล',
      duration: '4-12 weeks',
      durationTh: '4-12 สัปดาห์',
      suitableFor: 'Business professionals and managers',
      suitableForTh: 'นักธุรกิจและผู้จัดการ',
      priceDisplay: 'from $850/4 weeks',
      priceDisplayTh: 'เริ่มต้น ฿30,000/4 สัปดาห์',
      colorClass: 'bg-amber-500',
      badge: 'Professional',
      badgeTh: 'มืออาชีพ',
      features: ['Business Communication', 'Presentations', 'Email Writing', 'Negotiation Skills'],
      isFeatured: false,
      isActive: true,
      sortOrder: 4,
    },
    {
      slug: 'conversation-english',
      title: 'Conversation English',
      titleTh: 'ภาษาอังกฤษสนทนา',
      subtitle: 'Speak English confidently in any situation',
      subtitleTh: 'พูดภาษาอังกฤษได้อย่างมั่นใจในทุกสถานการณ์',
      iconName: 'MessageSquare',
      description: 'Focus on speaking and conversational English with native-style teachers for real-world communication.',
      descriptionTh: 'เน้นการพูดและการสนทนาภาษาอังกฤษกับครูสไตล์เจ้าของภาษาเพื่อการสื่อสารในชีวิตจริง',
      duration: '4-12 weeks',
      durationTh: '4-12 สัปดาห์',
      suitableFor: 'Anyone wanting to improve speaking confidence',
      suitableForTh: 'ทุกคนที่ต้องการพัฒนาความมั่นใจในการพูด',
      priceDisplay: 'from $680/4 weeks',
      priceDisplayTh: 'เริ่มต้น ฿24,000/4 สัปดาห์',
      colorClass: 'bg-pink-500',
      badge: 'Speaking Focus',
      badgeTh: 'เน้นการพูด',
      features: ['Daily Conversation Practice', 'Pronunciation Coaching', 'Role-Playing', 'Discussion Groups'],
      isFeatured: false,
      isActive: true,
      sortOrder: 5,
    },
    {
      slug: 'kids-english',
      title: "Kids' English Program",
      titleTh: 'โปรแกรมภาษาอังกฤษสำหรับเด็ก',
      subtitle: 'Fun and effective English for children',
      subtitleTh: 'ภาษาอังกฤษที่สนุกและมีประสิทธิภาพสำหรับเด็ก',
      iconName: 'Star',
      description: 'Special English program designed for children aged 6-15 with fun activities and structured learning.',
      descriptionTh: 'โปรแกรมภาษาอังกฤษพิเศษที่ออกแบบมาสำหรับเด็กอายุ 6-15 ปี พร้อมกิจกรรมสนุกสนานและการเรียนรู้ที่มีโครงสร้าง',
      duration: '4-12 weeks',
      durationTh: '4-12 สัปดาห์',
      suitableFor: 'Children aged 6-15 years',
      suitableForTh: 'เด็กอายุ 6-15 ปี',
      priceDisplay: 'from $600/4 weeks',
      priceDisplayTh: 'เริ่มต้น ฿21,000/4 สัปดาห์',
      colorClass: 'bg-yellow-500',
      badge: "Kid's Special",
      badgeTh: 'สำหรับเด็กโดยเฉพาะ',
      features: ['Fun Learning Activities', 'Storytelling', 'Games & Songs', 'Safe Environment'],
      isFeatured: false,
      isActive: true,
      sortOrder: 6,
    },
    {
      slug: 'academic-english',
      title: 'Academic English',
      titleTh: 'ภาษาอังกฤษเชิงวิชาการ',
      subtitle: 'English for university and academic purposes',
      subtitleTh: 'ภาษาอังกฤษสำหรับมหาวิทยาลัยและวัตถุประสงค์ทางวิชาการ',
      iconName: 'GraduationCap',
      description: 'Academic English program for students planning to attend English-speaking universities.',
      descriptionTh: 'โปรแกรมภาษาอังกฤษเชิงวิชาการสำหรับนักเรียนที่วางแผนจะเข้าเรียนที่มหาวิทยาลัยที่ใช้ภาษาอังกฤษ',
      duration: '8-24 weeks',
      durationTh: '8-24 สัปดาห์',
      suitableFor: 'University-bound students',
      suitableForTh: 'นักเรียนที่วางแผนเข้าศึกษามหาวิทยาลัย',
      priceDisplay: 'from $850/4 weeks',
      priceDisplayTh: 'เริ่มต้น ฿30,000/4 สัปดาห์',
      colorClass: 'bg-violet-500',
      badge: 'Academic',
      badgeTh: 'วิชาการ',
      features: ['Essay Writing', 'Research Skills', 'Academic Vocabulary', 'Presentation Skills'],
      isFeatured: false,
      isActive: true,
      sortOrder: 7,
    },
    {
      slug: 'toefl-preparation',
      title: 'TOEFL Preparation',
      titleTh: 'เตรียมสอบ TOEFL',
      subtitle: 'Master the TOEFL for US university admission',
      subtitleTh: 'เชี่ยวชาญ TOEFL เพื่อเข้าศึกษามหาวิทยาลัยในสหรัฐฯ',
      iconName: 'Award',
      description: 'Comprehensive TOEFL preparation covering all sections: Reading, Listening, Speaking, and Writing.',
      descriptionTh: 'การเตรียมสอบ TOEFL อย่างครอบคลุมครอบคลุมทุกส่วน: การอ่าน การฟัง การพูด และการเขียน',
      duration: '4-16 weeks',
      durationTh: '4-16 สัปดาห์',
      suitableFor: 'Students applying to US and Canadian universities',
      suitableForTh: 'นักเรียนที่สมัครเข้ามหาวิทยาลัยในสหรัฐฯ และแคนาดา',
      priceDisplay: 'from $920/4 weeks',
      priceDisplayTh: 'เริ่มต้น ฿33,000/4 สัปดาห์',
      colorClass: 'bg-cyan-500',
      badge: 'US University',
      badgeTh: 'มหาวิทยาลัยในสหรัฐฯ',
      features: ['TOEFL Mock Tests', 'All 4 Sections', 'Score Improvement', 'Online Practice'],
      isFeatured: false,
      isActive: true,
      sortOrder: 8,
    },
    {
      slug: 'volunteer-english',
      title: 'Volunteer + English Program',
      titleTh: 'โปรแกรมอาสาสมัคร + ภาษาอังกฤษ',
      subtitle: 'Learn English while giving back to the community',
      subtitleTh: 'เรียนภาษาอังกฤษไปพร้อมกับตอบแทนสังคม',
      iconName: 'Heart',
      description: 'Unique program combining English classes with community volunteer work in the Philippines.',
      descriptionTh: 'โปรแกรมสุดพิเศษที่รวมเรียนภาษาอังกฤษกับงานอาสาสมัครชุมชนในฟิลิปปินส์',
      duration: '4-12 weeks',
      durationTh: '4-12 สัปดาห์',
      suitableFor: 'Social-minded learners aged 18+',
      suitableForTh: 'ผู้เรียนที่มีจิตสาธารณะอายุ 18 ปีขึ้นไป',
      priceDisplay: 'from $750/4 weeks',
      priceDisplayTh: 'เริ่มต้น ฿26,500/4 สัปดาห์',
      colorClass: 'bg-rose-500',
      badge: 'Unique Experience',
      badgeTh: 'ประสบการณ์ไม่เหมือนใคร',
      features: ['English Classes', 'Volunteer Work', 'Cultural Exchange', 'Community Impact'],
      isFeatured: false,
      isActive: true,
      sortOrder: 9,
    },
    {
      slug: 'intensive-english',
      title: 'Intensive English Program',
      titleTh: 'โปรแกรมภาษาอังกฤษเข้มข้น',
      subtitle: 'Maximum improvement in minimum time',
      subtitleTh: 'พัฒนาสูงสุดในเวลาน้อยที่สุด',
      iconName: 'Zap',
      description: 'Our most intensive program with 8+ hours of English study per day for rapid improvement.',
      descriptionTh: 'โปรแกรมที่เข้มข้นที่สุดของเรา พร้อมการเรียนภาษาอังกฤษมากกว่า 8 ชั่วโมงต่อวันเพื่อพัฒนาอย่างรวดเร็ว',
      duration: '4-24 weeks',
      durationTh: '4-24 สัปดาห์',
      suitableFor: 'Motivated learners with limited time',
      suitableForTh: 'ผู้เรียนที่มีแรงจูงใจสูงและมีเวลาจำกัด',
      priceDisplay: 'from $950/4 weeks',
      priceDisplayTh: 'เริ่มต้น ฿34,000/4 สัปดาห์',
      colorClass: 'bg-red-500',
      badge: 'Fast Track',
      badgeTh: 'เร่งรัด',
      features: ['8+ Hours Daily', 'One-on-One & Group', 'Rapid Progress', 'Immersion Environment'],
      isFeatured: true,
      isActive: true,
      sortOrder: 10,
    },
    {
      slug: 'eap',
      title: 'English for Academic Purposes (EAP)',
      titleTh: 'ภาษาอังกฤษเพื่อวัตถุประสงค์ทางวิชาการ (EAP)',
      subtitle: 'Specialized English for academic success',
      subtitleTh: 'ภาษาอังกฤษเฉพาะทางเพื่อความสำเร็จทางวิชาการ',
      iconName: 'FileText',
      description: 'EAP is designed for students who need English skills for academic study in English-speaking environments.',
      descriptionTh: 'EAP ออกแบบมาสำหรับนักเรียนที่ต้องการทักษะภาษาอังกฤษสำหรับการศึกษาในสภาพแวดล้อมที่ใช้ภาษาอังกฤษ',
      duration: '8-24 weeks',
      durationTh: '8-24 สัปดาห์',
      suitableFor: 'Graduate and postgraduate students',
      suitableForTh: 'นักศึกษาระดับบัณฑิตศึกษาและหลังปริญญา',
      priceDisplay: 'from $880/4 weeks',
      priceDisplayTh: 'เริ่มต้น ฿31,500/4 สัปดาห์',
      colorClass: 'bg-slate-500',
      badge: 'Academic',
      badgeTh: 'วิชาการ',
      features: ['Academic Writing', 'Critical Thinking', 'Research Skills', 'Thesis Writing'],
      isFeatured: false,
      isActive: true,
      sortOrder: 11,
    },
    {
      slug: 'english-plus-internship',
      title: 'English + Internship',
      titleTh: 'ภาษาอังกฤษ + ฝึกงาน',
      subtitle: 'Learn English and gain work experience',
      subtitleTh: 'เรียนภาษาอังกฤษและได้รับประสบการณ์ทำงาน',
      iconName: 'Building',
      description: 'Combine English language learning with a real internship placement in the Philippines.',
      descriptionTh: 'ผสมผสานการเรียนภาษาอังกฤษกับการฝึกงานจริงในฟิลิปปินส์',
      duration: '12-24 weeks',
      durationTh: '12-24 สัปดาห์',
      suitableFor: 'Young professionals aged 18-30',
      suitableForTh: 'มืออาชีพรุ่นใหม่อายุ 18-30 ปี',
      priceDisplay: 'from $1,200/12 weeks',
      priceDisplayTh: 'เริ่มต้น ฿43,000/12 สัปดาห์',
      colorClass: 'bg-teal-500',
      badge: 'Work Experience',
      badgeTh: 'ประสบการณ์ทำงาน',
      features: ['English Classes', 'Internship Placement', 'Work Permit Support', 'Career Mentoring'],
      isFeatured: false,
      isActive: true,
      sortOrder: 12,
    },
  ]).onConflictDoNothing();

  // ─── Blog Posts ─────────────────────────────────────────────────────────────
  console.log('📝 Seeding blog posts...');
  await db.insert(blogPostsTable).values([
    {
      slug: 'why-study-english-in-philippines',
      title: 'Why Study English in the Philippines?',
      titleTh: 'ทำไมต้องเรียนภาษาอังกฤษในฟิลิปปินส์?',
      excerpt: 'Discover why the Philippines is the top destination for English language learning in Asia.',
      excerptTh: 'ค้นพบว่าทำไมฟิลิปปินส์จึงเป็นจุดหมายสูงสุดสำหรับการเรียนภาษาอังกฤษในเอเชีย',
      content: '# Why Study English in the Philippines?\n\nThe Philippines is one of the top English-speaking countries in Asia...',
      contentTh: '# ทำไมต้องเรียนภาษาอังกฤษในฟิลิปปินส์?\n\nฟิลิปปินส์เป็นหนึ่งในประเทศที่พูดภาษาอังกฤษชั้นนำในเอเชีย...',
      category: 'Tips & Guides',
      author: 'Philingo Team',
      authorTh: 'ทีม Philingo',
      tags: ['Philippines', 'English Learning', 'Study Abroad'],
      isFeatured: true,
      isPublished: true,
      publishedAt: new Date('2024-01-15'),
    },
    {
      slug: 'ielts-vs-toefl-which-is-right',
      title: 'IELTS vs TOEFL: Which Exam is Right for You?',
      titleTh: 'IELTS vs TOEFL: การสอบใดเหมาะกับคุณ?',
      excerpt: 'A comprehensive comparison of IELTS and TOEFL to help you choose the right exam.',
      excerptTh: 'การเปรียบเทียบ IELTS และ TOEFL อย่างครอบคลุมเพื่อช่วยคุณเลือกการสอบที่ถูกต้อง',
      content: '# IELTS vs TOEFL\n\nBoth IELTS and TOEFL are internationally recognized English proficiency tests...',
      contentTh: '# IELTS vs TOEFL\n\nทั้ง IELTS และ TOEFL เป็นการทดสอบความสามารถภาษาอังกฤษที่ได้รับการยอมรับในระดับสากล...',
      category: 'Exam Prep',
      author: 'Philingo Team',
      authorTh: 'ทีม Philingo',
      tags: ['IELTS', 'TOEFL', 'Exam Prep'],
      isFeatured: true,
      isPublished: true,
      publishedAt: new Date('2024-02-01'),
    },
    {
      slug: 'cebu-vs-baguio-which-city',
      title: 'Cebu vs Baguio: Which City Should You Study In?',
      titleTh: 'เซบู vs บาเกียว: ควรเรียนที่เมืองไหนดี?',
      excerpt: 'Compare the two most popular cities for English study in the Philippines.',
      excerptTh: 'เปรียบเทียบสองเมืองยอดนิยมสำหรับการเรียนภาษาอังกฤษในฟิลิปปินส์',
      content: '# Cebu vs Baguio\n\nWhen choosing where to study English in the Philippines...',
      contentTh: '# เซบู vs บาเกียว\n\nเมื่อเลือกที่จะเรียนภาษาอังกฤษในฟิลิปปินส์...',
      category: 'Destinations',
      author: 'Philingo Team',
      authorTh: 'ทีม Philingo',
      tags: ['Cebu', 'Baguio', 'Philippines', 'Study Abroad'],
      isFeatured: false,
      isPublished: true,
      publishedAt: new Date('2024-02-15'),
    },
    {
      slug: 'cost-of-studying-english-philippines',
      title: 'How Much Does It Cost to Study English in the Philippines?',
      titleTh: 'ค่าใช้จ่ายในการเรียนภาษาอังกฤษในฟิลิปปินส์เท่าไหร่?',
      excerpt: 'A detailed breakdown of all costs involved in studying English in the Philippines.',
      excerptTh: 'รายละเอียดค่าใช้จ่ายทั้งหมดที่เกี่ยวข้องกับการเรียนภาษาอังกฤษในฟิลิปปินส์',
      content: '# Cost of Studying English in the Philippines\n\nThe Philippines is known for being one of the most affordable...',
      contentTh: '# ค่าใช้จ่ายในการเรียนภาษาอังกฤษในฟิลิปปินส์\n\nฟิลิปปินส์ขึ้นชื่อว่าเป็นหนึ่งในที่ที่ราคาไม่แพง...',
      category: 'Tips & Guides',
      author: 'Philingo Team',
      authorTh: 'ทีม Philingo',
      tags: ['Budget', 'Philippines', 'Study Abroad'],
      isFeatured: false,
      isPublished: true,
      publishedAt: new Date('2024-03-01'),
    },
    {
      slug: 'how-to-choose-english-school-philippines',
      title: 'How to Choose the Right English School in the Philippines',
      titleTh: 'วิธีเลือกโรงเรียนภาษาอังกฤษที่ใช่ในฟิลิปปินส์',
      excerpt: 'Key factors to consider when choosing an English language school in the Philippines.',
      excerptTh: 'ปัจจัยสำคัญที่ต้องพิจารณาเมื่อเลือกโรงเรียนภาษาอังกฤษในฟิลิปปินส์',
      content: '# How to Choose the Right English School\n\nChoosing the right English school can make or break your learning experience...',
      contentTh: '# วิธีเลือกโรงเรียนภาษาอังกฤษที่ใช่\n\nการเลือกโรงเรียนภาษาอังกฤษที่ถูกต้องสามารถสร้างหรือทำลายประสบการณ์การเรียนรู้ของคุณได้...',
      category: 'Tips & Guides',
      author: 'Philingo Team',
      authorTh: 'ทีม Philingo',
      tags: ['Tips', 'School Selection', 'Philippines'],
      isFeatured: true,
      isPublished: true,
      publishedAt: new Date('2024-03-15'),
    },
    {
      slug: 'thailand-to-philippines-visa-guide',
      title: 'Thai Citizens: Complete Visa Guide for Studying in the Philippines',
      titleTh: 'คนไทย: คู่มือวีซ่าฉบับสมบูรณ์สำหรับการเรียนในฟิลิปปินส์',
      excerpt: 'Everything Thai citizens need to know about visas for studying English in the Philippines.',
      excerptTh: 'ทุกสิ่งที่คนไทยต้องรู้เกี่ยวกับวีซ่าสำหรับการเรียนภาษาอังกฤษในฟิลิปปินส์',
      content: '# Thai Citizens: Complete Visa Guide\n\nFor Thai citizens, entering the Philippines for short-term study is straightforward...',
      contentTh: '# คนไทย: คู่มือวีซ่าฉบับสมบูรณ์\n\nสำหรับคนไทย การเข้าฟิลิปปินส์เพื่อการศึกษาระยะสั้นเป็นเรื่องง่าย...',
      category: 'Visa & Travel',
      author: 'Philingo Team',
      authorTh: 'ทีม Philingo',
      tags: ['Visa', 'Thailand', 'Philippines', 'Travel'],
      isFeatured: false,
      isPublished: true,
      publishedAt: new Date('2024-04-01'),
    },
  ]).onConflictDoNothing();

  // ─── FAQs ────────────────────────────────────────────────────────────────────
  console.log('❓ Seeding FAQs...');
  await db.insert(faqsTable).values([
    {
      question: 'Why study English in the Philippines?',
      questionTh: 'ทำไมต้องเรียนภาษาอังกฤษในฟิลิปปินส์?',
      answer: 'The Philippines offers affordable English education with native-level English speakers, modern facilities, and a welcoming culture. It\'s one of the most cost-effective destinations in Asia for English study.',
      answerTh: 'ฟิลิปปินส์มีการศึกษาภาษาอังกฤษที่ราคาไม่แพงพร้อมผู้พูดภาษาอังกฤษระดับเจ้าของภาษา สิ่งอำนวยความสะดวกทันสมัย และวัฒนธรรมที่เป็นมิตร เป็นหนึ่งในจุดหมายปลายทางที่คุ้มค่าที่สุดในเอเชียสำหรับการเรียนภาษาอังกฤษ',
      category: 'General',
      isActive: true,
      sortOrder: 1,
    },
    {
      question: 'What is the average cost of studying English in the Philippines?',
      questionTh: 'ค่าใช้จ่ายเฉลี่ยในการเรียนภาษาอังกฤษในฟิลิปปินส์เท่าไหร่?',
      answer: 'The average cost ranges from $600-$1,200 per month including accommodation, meals, and tuition. This is significantly more affordable compared to studying in English-speaking countries like the US, UK, or Australia.',
      answerTh: 'ค่าใช้จ่ายเฉลี่ยอยู่ที่ประมาณ 21,000-43,000 บาทต่อเดือน รวมค่าที่พัก ค่าอาหาร และค่าเล่าเรียน ซึ่งราคาไม่แพงกว่าการเรียนในประเทศที่ใช้ภาษาอังกฤษอย่างสหรัฐฯ อังกฤษ หรือออสเตรเลียอย่างมาก',
      category: 'Costs',
      isActive: true,
      sortOrder: 2,
    },
    {
      question: 'Do I need a visa to study in the Philippines?',
      questionTh: 'ฉันต้องมีวีซ่าเพื่อเรียนในฟิลิปปินส์ไหม?',
      answer: 'Thai citizens can enter the Philippines without a visa for up to 30 days. For longer stays, you can extend your stay at the Bureau of Immigration. Schools often assist with visa extensions.',
      answerTh: 'คนไทยสามารถเข้าฟิลิปปินส์ได้โดยไม่ต้องมีวีซ่าสูงสุด 30 วัน สำหรับการพักนานขึ้น คุณสามารถต่อระยะเวลาพักได้ที่สำนักงานตรวจคนเข้าเมือง โรงเรียนมักช่วยเรื่องการต่อวีซ่า',
      category: 'Visa',
      isActive: true,
      sortOrder: 3,
    },
    {
      question: 'What is the minimum age to study at these schools?',
      questionTh: 'อายุขั้นต่ำในการเรียนที่โรงเรียนเหล่านี้คือเท่าไหร่?',
      answer: 'Most schools accept students aged 16 and above for adult programs. Some schools have special programs for children aged 6-15. Please check each school\'s specific requirements.',
      answerTh: 'โรงเรียนส่วนใหญ่รับนักเรียนอายุ 16 ปีขึ้นไปสำหรับโปรแกรมผู้ใหญ่ บางโรงเรียนมีโปรแกรมพิเศษสำหรับเด็กอายุ 6-15 ปี กรุณาตรวจสอบข้อกำหนดเฉพาะของแต่ละโรงเรียน',
      category: 'Eligibility',
      isActive: true,
      sortOrder: 4,
    },
    {
      question: 'What is the best time to study English in the Philippines?',
      questionTh: 'ช่วงเวลาที่ดีที่สุดในการเรียนภาษาอังกฤษในฟิลิปปินส์คือเมื่อไหร่?',
      answer: 'The Philippines is a year-round destination. The dry season (November to May) is generally the most popular time. The rainy season (June to October) can be great for lower prices and fewer students.',
      answerTh: 'ฟิลิปปินส์เป็นจุดหมายตลอดทั้งปี ฤดูแล้ง (พฤศจิกายนถึงพฤษภาคม) มักเป็นช่วงที่ได้รับความนิยมมากที่สุด ฤดูฝน (มิถุนายนถึงตุลาคม) อาจเป็นช่วงที่ดีสำหรับราคาที่ต่ำกว่าและนักเรียนน้อยกว่า',
      category: 'General',
      isActive: true,
      sortOrder: 5,
    },
    {
      question: 'What level of English do I need to start?',
      questionTh: 'ฉันต้องมีระดับภาษาอังกฤษเท่าไหร่จึงจะเริ่มเรียนได้?',
      answer: 'Most schools accept complete beginners. You will take a placement test on arrival to determine your current level, and you will be placed in the appropriate class.',
      answerTh: 'โรงเรียนส่วนใหญ่รับผู้เริ่มต้นอย่างสมบูรณ์ คุณจะทำแบบทดสอบการจัดระดับเมื่อมาถึงเพื่อกำหนดระดับปัจจุบันของคุณ และคุณจะถูกจัดในชั้นเรียนที่เหมาะสม',
      category: 'Eligibility',
      isActive: true,
      sortOrder: 6,
    },
    {
      question: 'Can I work while studying in the Philippines?',
      questionTh: 'ฉันสามารถทำงานขณะเรียนในฟิลิปปินส์ได้ไหม?',
      answer: 'Student visa holders are generally not permitted to work in the Philippines. We recommend focusing on your studies during your time there.',
      answerTh: 'ผู้ถือวีซ่านักเรียนโดยทั่วไปไม่ได้รับอนุญาตให้ทำงานในฟิลิปปินส์ เราแนะนำให้มุ่งเน้นการเรียนระหว่างที่อยู่ที่นั่น',
      category: 'Visa',
      isActive: true,
      sortOrder: 7,
    },
    {
      question: 'Does Philingo provide airport pickup?',
      questionTh: 'Philingo มีบริการรับส่งสนามบินไหม?',
      answer: 'Yes, we can arrange airport pickup for you through the school. This service usually costs $10-20 and can be arranged when you book your program.',
      answerTh: 'ใช่ เราสามารถจัดเตรียมบริการรับส่งสนามบินให้คุณผ่านทางโรงเรียน บริการนี้มักจะมีค่าใช้จ่ายประมาณ 350-700 บาท และสามารถจัดเตรียมได้เมื่อคุณจองโปรแกรม',
      category: 'Services',
      isActive: true,
      sortOrder: 8,
    },
    {
      question: 'What happens if I am not happy with my school?',
      questionTh: 'จะเกิดอะไรขึ้นถ้าฉันไม่พอใจกับโรงเรียนของฉัน?',
      answer: 'We provide ongoing support throughout your stay. If you have issues with your school, contact your Philingo advisor and we will help mediate or find alternative solutions.',
      answerTh: 'เราให้การสนับสนุนอย่างต่อเนื่องตลอดการพักของคุณ หากคุณมีปัญหากับโรงเรียน ติดต่อที่ปรึกษา Philingo ของคุณ และเราจะช่วยไกล่เกลี่ยหรือหาทางเลือกอื่น',
      category: 'Services',
      isActive: true,
      sortOrder: 9,
    },
    {
      question: 'How do I apply for a school through Philingo?',
      questionTh: 'ฉันสมัครเข้าโรงเรียนผ่าน Philingo ได้อย่างไร?',
      answer: 'Simply fill out our application form on the website or contact us via Line or Facebook. Our advisors will guide you through the entire process including school selection, enrollment, visa, and accommodation.',
      answerTh: 'เพียงกรอกแบบฟอร์มใบสมัครบนเว็บไซต์หรือติดต่อเราผ่าน Line หรือ Facebook ที่ปรึกษาของเราจะแนะนำคุณตลอดกระบวนการทั้งหมดรวมถึงการเลือกโรงเรียน การลงทะเบียน วีซ่า และที่พัก',
      category: 'Application',
      isActive: true,
      sortOrder: 10,
    },
  ]).onConflictDoNothing();

  // ─── Testimonials ────────────────────────────────────────────────────────────
  console.log('💬 Seeding testimonials...');
  await db.insert(testimonialsTable).values([
    {
      name: 'Somchai K.',
      nameTh: 'สมชาย ก.',
      school: 'SMEAG Capital',
      schoolTh: 'เอสเอ็มอีเอจี แคปิตอล',
      program: 'IELTS Preparation',
      scoreBefore: '5.0',
      scoreAfter: '7.0',
      content: 'After 12 weeks at SMEAG, my IELTS score jumped from 5.0 to 7.0. Philingo made everything so easy - from booking to visa support. I\'m now accepted at my dream university in Australia!',
      contentTh: 'หลังจาก 12 สัปดาห์ที่ SMEAG คะแนน IELTS ของฉันพุ่งจาก 5.0 เป็น 7.0 Philingo ทำให้ทุกอย่างง่ายมาก ตั้งแต่การจองไปจนถึงการสนับสนุนวีซ่า ตอนนี้ฉันได้รับการตอบรับจากมหาวิทยาลัยในฝันในออสเตรเลียแล้ว!',
      initials: 'SK',
      rating: 5,
      isFeatured: true,
      isActive: true,
      sortOrder: 1,
    },
    {
      name: 'Nattaya P.',
      nameTh: 'ณัฐยา พ.',
      school: 'CIA',
      schoolTh: 'ซีไอเอ',
      program: 'General English',
      content: 'I studied at CIA for 8 weeks and my English improved dramatically. The teachers are excellent and the facilities are world-class. Philingo\'s support before and during my stay was invaluable.',
      contentTh: 'ฉันเรียนที่ CIA 8 สัปดาห์และภาษาอังกฤษของฉันพัฒนาขึ้นอย่างมาก ครูยอดเยี่ยมมากและสิ่งอำนวยความสะดวกระดับโลก การสนับสนุนของ Philingo ก่อนและระหว่างการพักของฉันมีค่ามาก',
      initials: 'NP',
      rating: 5,
      isFeatured: true,
      isActive: true,
      sortOrder: 2,
    },
    {
      name: 'Arjun S.',
      nameTh: 'อาร์จัน ส.',
      school: 'QQ English',
      schoolTh: 'คิวคิว อิงลิช',
      program: 'TOEIC Preparation',
      scoreBefore: '550',
      scoreAfter: '850',
      content: 'QQ English is fantastic. The Circle Method really works! My TOEIC score went from 550 to 850 in just 8 weeks. I highly recommend Philingo for anyone looking to study in the Philippines.',
      contentTh: 'QQ English ยอดเยี่ยมมาก วิธี Circle Method ใช้ได้จริง! คะแนน TOEIC ของฉันไปจาก 550 เป็น 850 ในเพียง 8 สัปดาห์ ฉันแนะนำ Philingo อย่างยิ่งสำหรับทุกคนที่ต้องการเรียนในฟิลิปปินส์',
      initials: 'AS',
      rating: 5,
      isFeatured: true,
      isActive: true,
      sortOrder: 3,
    },
    {
      name: 'Wanida T.',
      nameTh: 'วนิดา ต.',
      school: 'PINES International',
      schoolTh: 'ไพนส์ อินเตอร์เนชั่นแนล',
      program: 'General English',
      content: 'Baguio is such a beautiful city and PINES is a great school. The cool weather makes studying so comfortable. Philingo helped me choose the right school for my goals.',
      contentTh: 'บาเกียวเป็นเมืองที่สวยงามมากและ PINES เป็นโรงเรียนที่ยอดเยี่ยม อากาศเย็นทำให้การเรียนสบายมาก Philingo ช่วยให้ฉันเลือกโรงเรียนที่เหมาะกับเป้าหมายของฉัน',
      initials: 'WT',
      rating: 5,
      isFeatured: false,
      isActive: true,
      sortOrder: 4,
    },
    {
      name: 'Chaichana B.',
      nameTh: 'ชัยชนะ บ.',
      school: "B'Cebu",
      schoolTh: 'บีเซบู',
      program: 'Intensive English',
      content: "B'Cebu has amazing facilities including an Olympic swimming pool! The teachers are professional and the study environment is excellent. I improved my English significantly in just 4 weeks.",
      contentTh: "B'Cebu มีสิ่งอำนวยความสะดวกที่น่าทึ่งรวมถึงสระว่ายน้ำโอลิมปิก! ครูเป็นมืออาชีพและสภาพแวดล้อมการเรียนยอดเยี่ยม ฉันพัฒนาภาษาอังกฤษอย่างมีนัยสำคัญในเพียง 4 สัปดาห์",
      initials: 'CB',
      rating: 4,
      isFeatured: false,
      isActive: true,
      sortOrder: 5,
    },
    {
      name: 'Malee R.',
      nameTh: 'มาลี ร.',
      school: 'Philinter',
      schoolTh: 'ฟิลอินเตอร์',
      program: 'IELTS Preparation',
      scoreBefore: '5.5',
      scoreAfter: '6.5',
      content: 'Philinter was the perfect choice for my budget. The one-on-one classes really accelerated my progress. Philingo\'s team was helpful throughout the entire process.',
      contentTh: 'Philinter เป็นตัวเลือกที่สมบูรณ์แบบสำหรับงบประมาณของฉัน ชั้นเรียนแบบตัวต่อตัวช่วยเร่งความก้าวหน้าของฉันจริงๆ ทีมของ Philingo ให้ความช่วยเหลือตลอดกระบวนการ',
      initials: 'MR',
      rating: 5,
      isFeatured: false,
      isActive: true,
      sortOrder: 6,
    },
  ]).onConflictDoNothing();

  // ─── Site Settings ───────────────────────────────────────────────────────────
  console.log('⚙️  Seeding site settings...');
  const settings = [
    { key: 'site_name', value: 'Philingo', group: 'general', label: 'Site Name' },
    { key: 'site_tagline', value: 'Study English, Live Philippines', group: 'general', label: 'Site Tagline' },
    { key: 'contact_email', value: 'info@philingo.com', group: 'contact', label: 'Contact Email' },
    { key: 'admin_email', value: 'admin@philingo.com', group: 'contact', label: 'Admin Email' },
    { key: 'phone', value: '+66 2 XXX XXXX', group: 'contact', label: 'Phone' },
    { key: 'line_id', value: '@philingo', group: 'social', label: 'LINE ID' },
    { key: 'facebook_url', value: 'https://facebook.com/philingo', group: 'social', label: 'Facebook URL' },
    { key: 'instagram_url', value: 'https://instagram.com/philingo', group: 'social', label: 'Instagram URL' },
    { key: 'youtube_url', value: 'https://youtube.com/@philingo', group: 'social', label: 'YouTube URL' },
    { key: 'site_url', value: 'https://philingo.com', group: 'general', label: 'Site URL' },
  ];

  for (const setting of settings) {
    await db.insert(siteSettingsTable).values(setting).onConflictDoNothing();
  }

  console.log('✅ Content seeding complete!');
  process.exit(0);
}

seedContent().catch((err) => {
  console.error('❌ Seed failed:', err);
  process.exit(1);
});
